import "@/styles/reset.scss";
import type { Metadata } from "next";
import { FC, ReactNode } from "react";

interface IProps {
    children: ReactNode;
}

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const RootLayout: FC<IProps> = ({ children }) => {
    return (
        <html lang="en">
            <body>{children}</body>
        </html>
    );
};

export default RootLayout;
